services:
  canopus:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    image: ghcr.io/endworks/canopus
    ports:
      - 3000:3000
    networks:
      - canopus

  canopus-zaragoza:
    build:
      context: .
      dockerfile: apps/zaragoza/Dockerfile
    image: ghcr.io/endworks/canopus-zaragoza
    ports:
      - 8877:3000
    environment:
      MONGODB_URI: ${MONGODB_URI:-}
    networks:
      - canopus
    depends_on:
      - canopus

  canopus-zine:
    build:
      context: .
      dockerfile: apps/zine/Dockerfile
    image: ghcr.io/endworks/canopus-zine
    ports:
      - 8878:3000
    environment:
      MONGODB_URI: ${MONGODB_URI:-}
      THE_MOVIE_DB_API_KEY: ${THE_MOVIE_DB_API_KEY:-}
    networks:
      - canopus
    depends_on:
      - canopus

  canopus-rae:
    build:
      context: .
      dockerfile: apps/rae/Dockerfile
    image: ghcr.io/endworks/canopus-rae
    ports:
      - 8879:3000
    networks:
      - canopus
    depends_on:
      - canopus

  canopus-twitter-downloader:
    build:
      context: .
      dockerfile: apps/twitter-downloader/Dockerfile
    image: ghcr.io/endworks/canopus-twitter-downloader
    ports:
      - 8876:3000
    environment:
      TWITTER_CLIENT_TOKEN: ${TWITTER_CLIENT_TOKEN:-}
    networks:
      - canopus
    depends_on:
      - canopus

networks:
  canopus:
    driver: bridge
